server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movieDB
    username: postgres
    password: 21wvtmykx
#    hikari:
#      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
